FROM ubuntu:18.04

LABEL maintainer <rene.gassmoeller@mailbox.org>

RUN apt-get update && apt-get -yq install \
    make \
    gfortran \
    g++ \
    git \
    libblas-dev \
    liblapack-dev \
    libfftw3-dev \
    libopenmpi-dev \
    nano

# Export compilers
ENV CC mpicc
ENV CXX mpicxx
ENV FC mpifort
